### PR TITLE
Delete Startup.vb

### PR DESCRIPTION
**Pull request by InteXX**
With the update of Program.vb to use the new Minimal API, this file is no longer needed.

### CODE REVIEW

**Comment by VBAndCs** [comment]
@InteXX 
I appreciate your contributions, and I will review them as soon as I finish the work in hand.
Thanks.

**Comment by InteXX** [comment]
Are you still active on Gitter?

**Comment by VBAndCs** [comment]
> Are you still active on Gitter?

No, but showtimes on [twitter](https://twitter.com/mhmd_hmdy)

**Comment by InteXX** [comment]
Ah, OK.

I'm a Twitter holdout myself, but I can always reach you here.

**Comment by InteXX** [comment]
@VBAndCs 

Any further thoughts on these two (related) PRs?

**Comment by VBAndCs** [comment]
@InteXX 
 I am off Vazor now, consumed by Small Visual Basic. Besides, .net 7 upcoming in 2 months, and it's practical to update Vazor to .net 7 for once. You have the template source now, and you can modify it for your own benefit, until I revisit vazor in .net 7 God willing.
Thanks.

**Comment by InteXX** [comment]
> you can modify it for your own benefit

Oh yes, of course. I already have. I was just offering the contribution so as to help others, that's all.

But I agree. At this stage of the game, it's better to see what .NET 7 has to offer. (Probably the same thing, I'd think.)

**Comment by InteXX** [comment]
I just learned that stale PRs are automatically closed after 180 days (+ a 5-day grace period). This means that these two will be closed later next week, and I'll have to resubmit them.

A quick review and test shouldn't take but a few minutes, I think. If it builds for you, you're more than halfway there.

I know you're wrapped up with sVB, but do you suppose you might give these a bit of attention, to save us more work in the long run? My proposed changes are pretty simple.

**Comment by VBAndCs** [comment]
@InteXX 
Done. But this will not update the VazorEx here nor on windows store.
Thanks.

**Comment by InteXX** [comment]
> But this will not update the VazorEx here nor on windows store

Right, I wouldn't have expected it to.

By 'Windows Store,' do you mean NuGet?

**Comment by VBAndCs** [comment]
Sorry, I mean VS market place:
https://marketplace.visualstudio.com/items?itemName=ModernVBNET.Vazor

**Comment by InteXX** [comment]
> VS Market Place

Gotcha.

**Pull request merged**
